/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'vie-du-club': VieDuClub;
    'membres-bureau': MembresBureau;
    activites: Activite;
    sorties: Sorty;
    galerie: Galerie;
    documents: Document;
    media: Media;
    users: User;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'vie-du-club': VieDuClubSelect<false> | VieDuClubSelect<true>;
    'membres-bureau': MembresBureauSelect<false> | MembresBureauSelect<true>;
    activites: ActivitesSelect<false> | ActivitesSelect<true>;
    sorties: SortiesSelect<false> | SortiesSelect<true>;
    galerie: GalerieSelect<false> | GalerieSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'flash-info': FlashInfo;
    tarifs: Tarif;
    parametres: Parametre;
    apparence: Apparence;
  };
  globalsSelect: {
    'flash-info': FlashInfoSelect<false> | FlashInfoSelect<true>;
    tarifs: TarifsSelect<false> | TarifsSelect<true>;
    parametres: ParametresSelect<false> | ParametresSelect<true>;
    apparence: ApparenceSelect<false> | ApparenceSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Actualités affichées sur la page d’accueil, section « Vie du club ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vie-du-club".
 */
export interface VieDuClub {
  id: number;
  titre: string;
  date: string;
  categorie: 'club' | 'sortie' | 'evenement';
  image?: (number | null) | Media;
  resume: string;
  /**
   * Choisissez une page, une activité ou une sortie du site.
   */
  lien?: {
    type?: ('aucun' | 'page' | 'activite' | 'sortie' | 'externe') | null;
    page?:
      | (
          | '/'
          | '/activites'
          | '/planning'
          | '/sorties-voyages'
          | '/galerie'
          | '/adhesion'
          | '/formation'
          | '/evenement'
          | '/statuts'
          | '/liens-utiles'
          | '/contact'
          | '/mentions-legales'
          | '/conditions-utilisation'
        )
      | null;
    activite?: (number | null) | Activite;
    sortie?: (number | null) | Sorty;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Toutes les photos du site. Ouvrez-en une puis « Modifier l’image » pour la recadrer ou choisir son point d’intérêt ; cochez-en plusieurs pour les ajouter à la galerie du site, ou en retirer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lue par les lecteurs d’écran : décrivez ce que montre la photo.
   */
  alt: string;
  /**
   * Auteur et licence si la photo ne vient pas du club.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Pages « Activités » et fiches du site. Une activité dépubliée (ou en brouillon seulement) disparaît du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites".
 */
export interface Activite {
  id: number;
  nom: string;
  /**
   * Affichée sur la carte de la page Activités et sous le titre de la fiche.
   */
  description: string;
  presentation?: string | null;
  niveau?: string | null;
  icone?: (number | null) | Media;
  photo?: (number | null) | Media;
  photos?: (number | Media)[] | null;
  creneaux?:
    | {
        jour: 'Lundi' | 'Mardi' | 'Mercredi' | 'Jeudi' | 'Vendredi' | 'Samedi' | 'Dimanche' | 'Voir planning';
        horaire: string;
        lieu: string;
        id?: string | null;
      }[]
    | null;
  pointRencontre?: string | null;
  /**
   * Position du point de rendez-vous. Laisser vide pour la détecter à partir du lieu.
   */
  carte?: {
    lieu?: string | null;
    lat?: number | null;
    lon?: number | null;
  };
  animateurs?:
    | {
        nom: string;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  infos?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Adresse de la fiche : /activite?id=<identifiant>. La changer casse les liens existants.
   */
  slug: string;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manifestations, sorties à la journée et voyages. Seuls les documents publiés apparaissent sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sorties".
 */
export interface Sorty {
  id: number;
  type: 'manifestation' | 'sortie' | 'voyage';
  titre: string;
  date: string;
  lieu: string;
  image?: (number | null) | Media;
  resume: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Section « Présentation du bureau » de la page d’accueil. Accord écrit des personnes requis pour la photo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres-bureau".
 */
export interface MembresBureau {
  id: number;
  nom: string;
  /**
   * Ex. : Présidente, Trésorier…
   */
  fonction: string;
  photo?: (number | null) | Media;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Page « Galerie photo » du site. Glissez les photos (poignée à gauche) pour changer leur ordre sur le site ; cochez-en plusieurs puis « Modifier » pour changer l’année ou la catégorie d’un coup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerie".
 */
export interface Galerie {
  id: number;
  _order?: string | null;
  photo: number | Media;
  legende?: string | null;
  annee: number;
  categorie: 'sport' | 'sortie' | 'vie';
  activite?:
    | (
        | 'marche-nordique'
        | 'tai-chi'
        | 'randonnee'
        | 'gymnastique'
        | 'tennis-de-table'
        | 'danse'
        | 'cyclisme'
        | 'aquagym'
        | 'petanque'
        | 'tennis'
        | 'atelier-memoire'
        | 'autres-sport'
        | 'autres-sorties'
        | 'vie-club'
        | 'autres'
      )
    | null;
  /**
   * Facultatif, ex. : Sortie au Touquet 2026.
   */
  album?: string | null;
  /**
   * Renseigné par l’import des photos du site.
   */
  fichierOrigine?: string | null;
  afficherSurSite?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents du club (PDF, Word, Excel, OpenDocument), listés sur la page « Liens utiles et documents ». Un document ne remplace un lien officiel (statuts, fiche d’adhésion…) que si vous le choisissez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  titre: string;
  categorie: 'adhesion' | 'vie-associative' | 'formations' | 'assurance' | 'autre';
  description?: string | null;
  /**
   * Le plus récent document choisi pour un lien officiel remplace le fichier actuel du site.
   */
  remplaceLienOfficiel: 'aucun' | 'statuts' | 'reglement' | 'adhesion' | 'assurance' | 'federal';
  afficherSurSite?: boolean | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nom: string;
  /**
   * Gère les bénévoles, les rôles, les paramètres et l’apparence du site.
   */
  estAdministrateur?: boolean | null;
  /**
   * Détermine les sections que le bénévole peut voir, modifier ou publier (menu Administration › Rôles).
   */
  roles?: (number | Role)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Chaque rôle regroupe des droits par section. Un bénévole peut avoir plusieurs rôles ; ses droits s’additionnent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  nom: string;
  description?: string | null;
  /**
   * « Voir » affiche la section dans l’administration. « Publier » permet de mettre en ligne ; sans ce droit, seuls les brouillons sont possibles.
   */
  permissions?:
    | {
        section:
          | 'vie-du-club'
          | 'membres-bureau'
          | 'activites'
          | 'sorties'
          | 'galerie'
          | 'documents'
          | 'media'
          | 'flash-info'
          | 'tarifs'
          | 'apparence';
        actions: ('voir' | 'creer' | 'modifier' | 'publier' | 'supprimer')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Laisser vide pour toutes les activités. Sinon, les droits sur la section « Activités » ne concernent que celles-ci (ex. : responsable Jeux de cartes).
   */
  activitesAutorisees?: (number | Activite)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vie-du-club';
        value: number | VieDuClub;
      } | null)
    | ({
        relationTo: 'membres-bureau';
        value: number | MembresBureau;
      } | null)
    | ({
        relationTo: 'activites';
        value: number | Activite;
      } | null)
    | ({
        relationTo: 'sorties';
        value: number | Sorty;
      } | null)
    | ({
        relationTo: 'galerie';
        value: number | Galerie;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vie-du-club_select".
 */
export interface VieDuClubSelect<T extends boolean = true> {
  titre?: T;
  date?: T;
  categorie?: T;
  image?: T;
  resume?: T;
  lien?:
    | T
    | {
        type?: T;
        page?: T;
        activite?: T;
        sortie?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres-bureau_select".
 */
export interface MembresBureauSelect<T extends boolean = true> {
  nom?: T;
  fonction?: T;
  photo?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites_select".
 */
export interface ActivitesSelect<T extends boolean = true> {
  nom?: T;
  description?: T;
  presentation?: T;
  niveau?: T;
  icone?: T;
  photo?: T;
  photos?: T;
  creneaux?:
    | T
    | {
        jour?: T;
        horaire?: T;
        lieu?: T;
        id?: T;
      };
  pointRencontre?: T;
  carte?:
    | T
    | {
        lieu?: T;
        lat?: T;
        lon?: T;
      };
  animateurs?:
    | T
    | {
        nom?: T;
        photo?: T;
        id?: T;
      };
  infos?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  slug?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sorties_select".
 */
export interface SortiesSelect<T extends boolean = true> {
  type?: T;
  titre?: T;
  date?: T;
  lieu?: T;
  image?: T;
  resume?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerie_select".
 */
export interface GalerieSelect<T extends boolean = true> {
  _order?: T;
  photo?: T;
  legende?: T;
  annee?: T;
  categorie?: T;
  activite?: T;
  album?: T;
  fichierOrigine?: T;
  afficherSurSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  titre?: T;
  categorie?: T;
  description?: T;
  remplaceLienOfficiel?: T;
  afficherSurSite?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nom?: T;
  estAdministrateur?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  nom?: T;
  description?: T;
  permissions?:
    | T
    | {
        section?: T;
        actions?: T;
        id?: T;
      };
  activitesAutorisees?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Bandeau défilant de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-info".
 */
export interface FlashInfo {
  id: number;
  actif?: boolean | null;
  message: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Grille tarifaire de la page Adhésion, affichée dans l’ordre saisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs".
 */
export interface Tarif {
  id: number;
  lignes?:
    | {
        montant: string;
        libelle: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chiffres clés et adresses de contact affichés sur le site. Réservé à l’administrateur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  depuis?: string | null;
  adherents?: string | null;
  activites?: string | null;
  emailContact?: string | null;
  emailSorties?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Polices, couleurs et en-têtes de pages. Chaque enregistrement est conservé : onglet « Versions » › « Restaurer » pour revenir en arrière.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparence".
 */
export interface Apparence {
  id: number;
  /**
   * Titre principal de chaque page.
   */
  policeTitres:
    'defaut' | 'Inter' | 'Manrope' | 'Poppins' | 'Lato' | 'Open Sans' | 'Nunito' | 'Merriweather' | 'Source Serif 4';
  /**
   * Titres des sections.
   */
  policeSousTitres:
    'defaut' | 'Inter' | 'Manrope' | 'Poppins' | 'Lato' | 'Open Sans' | 'Nunito' | 'Merriweather' | 'Source Serif 4';
  /**
   * Paragraphes, menus et boutons.
   */
  policeTexte:
    'defaut' | 'Inter' | 'Manrope' | 'Poppins' | 'Lato' | 'Open Sans' | 'Nunito' | 'Merriweather' | 'Source Serif 4';
  /**
   * Menus, titres et bandeaux (bleu d’origine).
   */
  couleurPrincipale: string;
  /**
   * Tous les boutons (survol compris) et textes mis en valeur (vert d’origine).
   */
  couleurSecondaire: string;
  /**
   * Bandeaux et détails (bleu-vert d’origine).
   */
  couleurAccent: string;
  /**
   * Image du bandeau de toutes les pages. L’image propre à une page (onglet « En-têtes de pages ») reste prioritaire.
   */
  imageEnTete?: (number | null) | Media;
  /**
   * Voile posé sur l’image pour garder le texte blanc lisible (bleu d’origine).
   */
  teinteEnTete: string;
  /**
   * Opacité du voile : 0 % laisse l’image nette, 100 % la rend opaque.
   */
  intensiteTeinte: number;
  /**
   * Remplace le titre, le sous-titre ou l’image d’en-tête d’une page. Champ vide = contenu actuel conservé.
   */
  enTetes?:
    | {
        page:
          | '/'
          | '/activites'
          | '/planning'
          | '/sorties-voyages'
          | '/galerie'
          | '/adhesion'
          | '/formation'
          | '/evenement'
          | '/statuts'
          | '/liens-utiles'
          | '/contact'
          | '/mentions-legales'
          | '/conditions-utilisation';
        titre?: string | null;
        sousTitre?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  valeursOrigine?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-info_select".
 */
export interface FlashInfoSelect<T extends boolean = true> {
  actif?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs_select".
 */
export interface TarifsSelect<T extends boolean = true> {
  lignes?:
    | T
    | {
        montant?: T;
        libelle?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  depuis?: T;
  adherents?: T;
  activites?: T;
  emailContact?: T;
  emailSorties?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apparence_select".
 */
export interface ApparenceSelect<T extends boolean = true> {
  policeTitres?: T;
  policeSousTitres?: T;
  policeTexte?: T;
  couleurPrincipale?: T;
  couleurSecondaire?: T;
  couleurAccent?: T;
  imageEnTete?: T;
  teinteEnTete?: T;
  intensiteTeinte?: T;
  enTetes?:
    | T
    | {
        page?: T;
        titre?: T;
        sousTitre?: T;
        image?: T;
        id?: T;
      };
  valeursOrigine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}