/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'vie-du-club': VieDuClub;
    'membres-bureau': MembresBureau;
    activites: Activite;
    sorties: Sorty;
    galerie: Galerie;
    documents: Document;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'vie-du-club': VieDuClubSelect<false> | VieDuClubSelect<true>;
    'membres-bureau': MembresBureauSelect<false> | MembresBureauSelect<true>;
    activites: ActivitesSelect<false> | ActivitesSelect<true>;
    sorties: SortiesSelect<false> | SortiesSelect<true>;
    galerie: GalerieSelect<false> | GalerieSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'flash-info': FlashInfo;
    tarifs: Tarif;
    parametres: Parametre;
  };
  globalsSelect: {
    'flash-info': FlashInfoSelect<false> | FlashInfoSelect<true>;
    tarifs: TarifsSelect<false> | TarifsSelect<true>;
    parametres: ParametresSelect<false> | ParametresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Actualités affichées sur la page d’accueil, section « Vie du club ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vie-du-club".
 */
export interface VieDuClub {
  id: number;
  titre: string;
  date: string;
  categorie: 'club' | 'sortie' | 'evenement';
  image?: (number | null) | Media;
  resume: string;
  lien?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lue par les lecteurs d’écran : décrivez ce que montre la photo.
   */
  alt: string;
  /**
   * Auteur et licence si la photo ne vient pas du club.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Section « Présentation du bureau » de la page d’accueil. Accord écrit des personnes requis pour la photo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres-bureau".
 */
export interface MembresBureau {
  id: number;
  nom: string;
  /**
   * Ex. : Présidente, Trésorier…
   */
  fonction: string;
  photo?: (number | null) | Media;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Chaque responsable ne voit et ne modifie que les activités dont il est référent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites".
 */
export interface Activite {
  id: number;
  nom: string;
  icone?: (number | null) | Media;
  description: string;
  presentation?: string | null;
  creneaux?:
    | {
        jour: 'Lundi' | 'Mardi' | 'Mercredi' | 'Jeudi' | 'Vendredi' | 'Samedi' | 'Dimanche' | 'Voir planning';
        horaire: string;
        lieu: string;
        id?: string | null;
      }[]
    | null;
  pointRencontre?: string | null;
  infos?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Seul un administrateur peut changer les référents.
   */
  referents?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nom: string;
  /**
   * Détermine les sections que le bénévole peut modifier.
   */
  roles: ('admin' | 'bureau' | 'activites' | 'sorties' | 'galerie')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manifestations, sorties à la journée et voyages. Seuls les documents publiés apparaissent sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sorties".
 */
export interface Sorty {
  id: number;
  type: 'manifestation' | 'sortie' | 'voyage';
  titre: string;
  date: string;
  lieu: string;
  image?: (number | null) | Media;
  resume: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos mises en avant sur le site, regroupées par album et par année.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerie".
 */
export interface Galerie {
  id: number;
  album?: string | null;
  annee?: number | null;
  photo: number | Media;
  legende?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Statuts, règlement intérieur, fiche d’adhésion, assurance, imprimé fédéral.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  titre: string;
  rubrique: 'statuts' | 'reglement' | 'adhesion' | 'assurance' | 'federal' | 'autre';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vie-du-club';
        value: number | VieDuClub;
      } | null)
    | ({
        relationTo: 'membres-bureau';
        value: number | MembresBureau;
      } | null)
    | ({
        relationTo: 'activites';
        value: number | Activite;
      } | null)
    | ({
        relationTo: 'sorties';
        value: number | Sorty;
      } | null)
    | ({
        relationTo: 'galerie';
        value: number | Galerie;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vie-du-club_select".
 */
export interface VieDuClubSelect<T extends boolean = true> {
  titre?: T;
  date?: T;
  categorie?: T;
  image?: T;
  resume?: T;
  lien?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membres-bureau_select".
 */
export interface MembresBureauSelect<T extends boolean = true> {
  nom?: T;
  fonction?: T;
  photo?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activites_select".
 */
export interface ActivitesSelect<T extends boolean = true> {
  nom?: T;
  icone?: T;
  description?: T;
  presentation?: T;
  creneaux?:
    | T
    | {
        jour?: T;
        horaire?: T;
        lieu?: T;
        id?: T;
      };
  pointRencontre?: T;
  infos?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  referents?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sorties_select".
 */
export interface SortiesSelect<T extends boolean = true> {
  type?: T;
  titre?: T;
  date?: T;
  lieu?: T;
  image?: T;
  resume?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerie_select".
 */
export interface GalerieSelect<T extends boolean = true> {
  album?: T;
  annee?: T;
  photo?: T;
  legende?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  titre?: T;
  rubrique?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nom?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Bandeau défilant de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-info".
 */
export interface FlashInfo {
  id: number;
  actif?: boolean | null;
  message: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Grille tarifaire de la page Adhésion, affichée dans l’ordre saisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs".
 */
export interface Tarif {
  id: number;
  lignes?:
    | {
        montant: string;
        libelle: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Chiffres clés et adresses de contact affichés sur le site. Réservé à l’administrateur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  depuis?: string | null;
  adherents?: string | null;
  activites?: string | null;
  emailContact?: string | null;
  emailSorties?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flash-info_select".
 */
export interface FlashInfoSelect<T extends boolean = true> {
  actif?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs_select".
 */
export interface TarifsSelect<T extends boolean = true> {
  lignes?:
    | T
    | {
        montant?: T;
        libelle?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  depuis?: T;
  adherents?: T;
  activites?: T;
  emailContact?: T;
  emailSorties?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}