import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "titres" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"vie_du_club_surtitre" varchar DEFAULT '',
  	"vie_du_club_titre" varchar DEFAULT 'Vie du club',
  	"vie_du_club_mot_mis_en_valeur" varchar DEFAULT 'club',
  	"vie_du_club_introduction" varchar DEFAULT '',
  	"qui_sommes_nous_surtitre" varchar DEFAULT '',
  	"qui_sommes_nous_titre" varchar DEFAULT 'Qui sommes-nous ?',
  	"qui_sommes_nous_mot_mis_en_valeur" varchar DEFAULT 'nous',
  	"qui_sommes_nous_introduction" varchar DEFAULT '',
  	"activites_surtitre" varchar DEFAULT 'Choisissez votre activité',
  	"activites_titre" varchar DEFAULT 'Quelle activité vous donne envie de bouger ?',
  	"activites_mot_mis_en_valeur" varchar DEFAULT 'bouger',
  	"activites_introduction" varchar DEFAULT 'Sélectionnez une icône pour découvrir sa fiche, ses horaires et les informations pratiques.',
  	"adhesion_surtitre" varchar DEFAULT '',
  	"adhesion_titre" varchar DEFAULT 'Formulaire d''Adhésion',
  	"adhesion_mot_mis_en_valeur" varchar DEFAULT 'Adhésion',
  	"adhesion_introduction" varchar DEFAULT 'Rejoignez le CBRS ! Remplissez ce formulaire et nous vous contacterons pour finaliser votre inscription.',
  	"nous_contacter_surtitre" varchar DEFAULT '',
  	"nous_contacter_titre" varchar DEFAULT 'Nous contacter',
  	"nous_contacter_mot_mis_en_valeur" varchar DEFAULT 'contacter',
  	"nous_contacter_introduction" varchar DEFAULT '',
  	"nous_trouver_surtitre" varchar DEFAULT '',
  	"nous_trouver_titre" varchar DEFAULT 'Nous trouver',
  	"nous_trouver_mot_mis_en_valeur" varchar DEFAULT 'trouver',
  	"nous_trouver_introduction" varchar DEFAULT '',
  	"fiches_formation_surtitre" varchar DEFAULT '',
  	"fiches_formation_titre" varchar DEFAULT 'Fiches formation par activité',
  	"fiches_formation_mot_mis_en_valeur" varchar DEFAULT 'activité',
  	"fiches_formation_introduction" varchar DEFAULT '',
  	"galerie_surtitre" varchar DEFAULT 'Explorer la galerie',
  	"galerie_titre" varchar DEFAULT 'Nos plus beaux souvenirs',
  	"galerie_mot_mis_en_valeur" varchar DEFAULT 'souvenirs',
  	"galerie_introduction" varchar DEFAULT 'Revivez les moments qui nous rassemblent : sorties, activités, sourires et souvenirs partagés.',
  	"ressources_surtitre" varchar DEFAULT 'Partenaires',
  	"ressources_titre" varchar DEFAULT 'Les ressources du club',
  	"ressources_mot_mis_en_valeur" varchar DEFAULT 'club',
  	"ressources_introduction" varchar DEFAULT 'Les partenaires et ressources qui accompagnent la vie du club.',
  	"documents_surtitre" varchar DEFAULT '',
  	"documents_titre" varchar DEFAULT 'Documents à télécharger',
  	"documents_mot_mis_en_valeur" varchar DEFAULT 'télécharger',
  	"documents_introduction" varchar DEFAULT '',
  	"planning_surtitre" varchar DEFAULT 'Semaine type',
  	"planning_titre" varchar DEFAULT 'Planning hebdomadaire',
  	"planning_mot_mis_en_valeur" varchar DEFAULT 'hebdomadaire',
  	"planning_introduction" varchar DEFAULT 'Toutes les activités, jours, horaires et lieux.',
  	"manifestations_surtitre" varchar DEFAULT 'Vie du club',
  	"manifestations_titre" varchar DEFAULT 'Nos manifestations',
  	"manifestations_mot_mis_en_valeur" varchar DEFAULT 'manifestations',
  	"manifestations_introduction" varchar DEFAULT 'Les grands rendez-vous et journées festives de la vie du club.',
  	"sorties_surtitre" varchar DEFAULT 'À la journée',
  	"sorties_titre" varchar DEFAULT 'Nos sorties',
  	"sorties_mot_mis_en_valeur" varchar DEFAULT 'sorties',
  	"sorties_introduction" varchar DEFAULT 'Le club organise régulièrement des sorties à la journée pour ses adhérents.',
  	"voyages_surtitre" varchar DEFAULT 'Plusieurs jours',
  	"voyages_titre" varchar DEFAULT 'Nos voyages',
  	"voyages_mot_mis_en_valeur" varchar DEFAULT 'voyages',
  	"voyages_introduction" varchar DEFAULT 'Le programme des prochains voyages sera publié ici. Pour toute information, contactez l’équipe organisatrice.',
  	"statuts_surtitre" varchar DEFAULT 'Vie associative',
  	"statuts_titre" varchar DEFAULT 'Statuts et règlement intérieur',
  	"statuts_mot_mis_en_valeur" varchar DEFAULT 'règlement intérieur',
  	"statuts_introduction" varchar DEFAULT 'Le Club du Beauvaisis de la Retraite Sportive est une association loi 1901. Ses statuts et son règlement intérieur définissent son objet, son organisation et les règles de vie communes à tous les adhérents.',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_titres_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_vie_du_club_surtitre" varchar DEFAULT '',
  	"version_vie_du_club_titre" varchar DEFAULT 'Vie du club',
  	"version_vie_du_club_mot_mis_en_valeur" varchar DEFAULT 'club',
  	"version_vie_du_club_introduction" varchar DEFAULT '',
  	"version_qui_sommes_nous_surtitre" varchar DEFAULT '',
  	"version_qui_sommes_nous_titre" varchar DEFAULT 'Qui sommes-nous ?',
  	"version_qui_sommes_nous_mot_mis_en_valeur" varchar DEFAULT 'nous',
  	"version_qui_sommes_nous_introduction" varchar DEFAULT '',
  	"version_activites_surtitre" varchar DEFAULT 'Choisissez votre activité',
  	"version_activites_titre" varchar DEFAULT 'Quelle activité vous donne envie de bouger ?',
  	"version_activites_mot_mis_en_valeur" varchar DEFAULT 'bouger',
  	"version_activites_introduction" varchar DEFAULT 'Sélectionnez une icône pour découvrir sa fiche, ses horaires et les informations pratiques.',
  	"version_adhesion_surtitre" varchar DEFAULT '',
  	"version_adhesion_titre" varchar DEFAULT 'Formulaire d''Adhésion',
  	"version_adhesion_mot_mis_en_valeur" varchar DEFAULT 'Adhésion',
  	"version_adhesion_introduction" varchar DEFAULT 'Rejoignez le CBRS ! Remplissez ce formulaire et nous vous contacterons pour finaliser votre inscription.',
  	"version_nous_contacter_surtitre" varchar DEFAULT '',
  	"version_nous_contacter_titre" varchar DEFAULT 'Nous contacter',
  	"version_nous_contacter_mot_mis_en_valeur" varchar DEFAULT 'contacter',
  	"version_nous_contacter_introduction" varchar DEFAULT '',
  	"version_nous_trouver_surtitre" varchar DEFAULT '',
  	"version_nous_trouver_titre" varchar DEFAULT 'Nous trouver',
  	"version_nous_trouver_mot_mis_en_valeur" varchar DEFAULT 'trouver',
  	"version_nous_trouver_introduction" varchar DEFAULT '',
  	"version_fiches_formation_surtitre" varchar DEFAULT '',
  	"version_fiches_formation_titre" varchar DEFAULT 'Fiches formation par activité',
  	"version_fiches_formation_mot_mis_en_valeur" varchar DEFAULT 'activité',
  	"version_fiches_formation_introduction" varchar DEFAULT '',
  	"version_galerie_surtitre" varchar DEFAULT 'Explorer la galerie',
  	"version_galerie_titre" varchar DEFAULT 'Nos plus beaux souvenirs',
  	"version_galerie_mot_mis_en_valeur" varchar DEFAULT 'souvenirs',
  	"version_galerie_introduction" varchar DEFAULT 'Revivez les moments qui nous rassemblent : sorties, activités, sourires et souvenirs partagés.',
  	"version_ressources_surtitre" varchar DEFAULT 'Partenaires',
  	"version_ressources_titre" varchar DEFAULT 'Les ressources du club',
  	"version_ressources_mot_mis_en_valeur" varchar DEFAULT 'club',
  	"version_ressources_introduction" varchar DEFAULT 'Les partenaires et ressources qui accompagnent la vie du club.',
  	"version_documents_surtitre" varchar DEFAULT '',
  	"version_documents_titre" varchar DEFAULT 'Documents à télécharger',
  	"version_documents_mot_mis_en_valeur" varchar DEFAULT 'télécharger',
  	"version_documents_introduction" varchar DEFAULT '',
  	"version_planning_surtitre" varchar DEFAULT 'Semaine type',
  	"version_planning_titre" varchar DEFAULT 'Planning hebdomadaire',
  	"version_planning_mot_mis_en_valeur" varchar DEFAULT 'hebdomadaire',
  	"version_planning_introduction" varchar DEFAULT 'Toutes les activités, jours, horaires et lieux.',
  	"version_manifestations_surtitre" varchar DEFAULT 'Vie du club',
  	"version_manifestations_titre" varchar DEFAULT 'Nos manifestations',
  	"version_manifestations_mot_mis_en_valeur" varchar DEFAULT 'manifestations',
  	"version_manifestations_introduction" varchar DEFAULT 'Les grands rendez-vous et journées festives de la vie du club.',
  	"version_sorties_surtitre" varchar DEFAULT 'À la journée',
  	"version_sorties_titre" varchar DEFAULT 'Nos sorties',
  	"version_sorties_mot_mis_en_valeur" varchar DEFAULT 'sorties',
  	"version_sorties_introduction" varchar DEFAULT 'Le club organise régulièrement des sorties à la journée pour ses adhérents.',
  	"version_voyages_surtitre" varchar DEFAULT 'Plusieurs jours',
  	"version_voyages_titre" varchar DEFAULT 'Nos voyages',
  	"version_voyages_mot_mis_en_valeur" varchar DEFAULT 'voyages',
  	"version_voyages_introduction" varchar DEFAULT 'Le programme des prochains voyages sera publié ici. Pour toute information, contactez l’équipe organisatrice.',
  	"version_statuts_surtitre" varchar DEFAULT 'Vie associative',
  	"version_statuts_titre" varchar DEFAULT 'Statuts et règlement intérieur',
  	"version_statuts_mot_mis_en_valeur" varchar DEFAULT 'règlement intérieur',
  	"version_statuts_introduction" varchar DEFAULT 'Le Club du Beauvaisis de la Retraite Sportive est une association loi 1901. Ses statuts et son règlement intérieur définissent son objet, son organisation et les règles de vie communes à tous les adhérents.',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "formation" ADD COLUMN "parcours_mot_mis_en_valeur" varchar DEFAULT 'animateur';
  ALTER TABLE "_formation_v" ADD COLUMN "version_parcours_mot_mis_en_valeur" varchar DEFAULT 'animateur';
  CREATE INDEX "_titres_v_created_at_idx" ON "_titres_v" USING btree ("created_at");
  CREATE INDEX "_titres_v_updated_at_idx" ON "_titres_v" USING btree ("updated_at");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "titres" CASCADE;
  DROP TABLE "_titres_v" CASCADE;
  ALTER TABLE "formation" DROP COLUMN "parcours_mot_mis_en_valeur";
  ALTER TABLE "_formation_v" DROP COLUMN "version_parcours_mot_mis_en_valeur";`)
}
